### ISSUE TITLE
Возможность работать над проектом

### ISSUE THREAD

**Issue by idkravitz** [DevAlone/pikagraphs#1]
Доброго времени суток,
Хотел бы немного помочь вашей разработке в меру своих сил, поэтому хотел бы спросить - можете ли вы выложить весь исходный код (например в модуле bot отсутствует модуль api, который там же и используется и по-видимости отвечает за сетевое взаимодействие с API самого Pikabu)

**Comment by DevAlone** [comment]
Здравствуйте! 

К сожалению я не планирую делать код для работы с API публичным, это может создать много проблем для пикабу, если кто-то начнёт его использовать во вред.
